const DATAFETCH = {
    DATA_LOAD: 'DATA_LOAD',
    DATA_LOAD_SUCCESS: 'DATA_LOAD_SUCCESS',
    DATA_LOAD_FAIL: 'DATA_LOAD_FAIL',
};

const COUNTER = {
    INCREASE_COUNTER: 'INCREASE_COUNTER',
    DECREASE_COUNTER: 'DECREASE_COUNTER',
    INCREASE_COUNTER_ASYNC: 'INCREASE_COUNTER_ASYNC',
    DECREASE_COUNTER_ASYNC: 'DECREASE_COUNTER_ASYNC'

};

const QUOTES = {
    QUOTES_LOAD: 'QUOTES_LOAD',
    QUOTES_LOAD_SUCCESS: 'QUOTES_LOAD_SUCCESS',
    QUOTES_LOAD_FAIL: 'QUOTES_LOAD_FAIL',
    QUOTES_AVAILABLE : 'QUOTES_AVAILABLE',
    ADD_QUOTE : 'ADD_QUOTE',
    UPDATE_QUOTE : 'UPDATE_QUOTE',
    DELETE_QUOTE : 'DELETE_QUOTE'
}



export {
    DATAFETCH ,
    COUNTER,
    QUOTES
};