const DATAFETCH = {
    DATA_LOAD: 'DATA_LOAD',
    DATA_LOAD_SUCCESS: 'DATA_LOAD_SUCCESS',
    DATA_LOAD_FAIL: 'DATA_LOAD_FAIL',
};

const COUNTER = {
    INCREASE_COUNTER: 'INCREASE_COUNTER',
    DECREASE_COUNTER: 'DECREASE_COUNTER',
    INCREASE_COUNTER_ASYNC: 'INCREASE_COUNTER_ASYNC',
    DECREASE_COUNTER_ASYNC: 'DECREASE_COUNTER_ASYNC'

};

export {
    DATAFETCH ,
    COUNTER
};